package com.victor.practicahibernate;

// Generated 14-feb-2014 1:27:39 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Circuitos generated by hbm2java
 */
@Entity
@Table(name = "circuitos", catalog = "hibernatevtm")
public class Circuitos implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String ubicacion;
	private Integer distancia;
	private Set<Pilotos> pilotoses = new HashSet<Pilotos>(0);

	public Circuitos() {
	}

	public Circuitos(String nombre, String ubicacion, Integer distancia,
			Set<Pilotos> pilotoses) {
		this.nombre = nombre;
		this.ubicacion = ubicacion;
		this.distancia = distancia;
		this.pilotoses = pilotoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ubicacion", length = 50)
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	@Column(name = "distancia")
	public Integer getDistancia() {
		return this.distancia;
	}

	public void setDistancia(Integer distancia) {
		this.distancia = distancia;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "pilotos_circuitos", catalog = "hibernatevtm", joinColumns = { @JoinColumn(name = "id_circuitos", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_pilotos", nullable = false, updatable = false) })
	public Set<Pilotos> getPilotoses() {
		return this.pilotoses;
	}

	public void setPilotoses(Set<Pilotos> pilotoses) {
		this.pilotoses = pilotoses;
	}

}
