package com.victor.practicahibernate;

// Generated 14-feb-2014 1:27:39 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Equipos generated by hbm2java
 */
@Entity
@Table(name = "equipos", catalog = "hibernatevtm")
public class Equipos implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String fundador;
	private String presidente;
	private Set<Pilotos> pilotoses = new HashSet<Pilotos>(0);
	private Set<Coches> cocheses = new HashSet<Coches>(0);
	private Set<Sponsors> sponsorses = new HashSet<Sponsors>(0);

	public Equipos() {
	}

	public Equipos(String nombre, String fundador, String presidente,
			Set<Pilotos> pilotoses, Set<Coches> cocheses,
			Set<Sponsors> sponsorses) {
		this.nombre = nombre;
		this.fundador = fundador;
		this.presidente = presidente;
		this.pilotoses = pilotoses;
		this.cocheses = cocheses;
		this.sponsorses = sponsorses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "fundador", length = 30)
	public String getFundador() {
		return this.fundador;
	}

	public void setFundador(String fundador) {
		this.fundador = fundador;
	}

	@Column(name = "presidente", length = 30)
	public String getPresidente() {
		return this.presidente;
	}

	public void setPresidente(String presidente) {
		this.presidente = presidente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipos")
	public Set<Pilotos> getPilotoses() {
		return this.pilotoses;
	}

	public void setPilotoses(Set<Pilotos> pilotoses) {
		this.pilotoses = pilotoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipos")
	public Set<Coches> getCocheses() {
		return this.cocheses;
	}

	public void setCocheses(Set<Coches> cocheses) {
		this.cocheses = cocheses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "equipos_sponsors", catalog = "hibernatevtm", joinColumns = { @JoinColumn(name = "id_equipos", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_sponsors", nullable = false, updatable = false) })
	public Set<Sponsors> getSponsorses() {
		return this.sponsorses;
	}

	public void setSponsorses(Set<Sponsors> sponsorses) {
		this.sponsorses = sponsorses;
	}

}
