package com.victor.practicahibernate;

// Generated 14-feb-2014 1:27:39 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ruedas generated by hbm2java
 */
@Entity
@Table(name = "ruedas", catalog = "hibernatevtm")
public class Ruedas implements java.io.Serializable {

	private Integer id;
	private Coches coches;
	private Integer pulgadas;
	private String tipoNeumatico;
	private Integer peso;

	public Ruedas() {
	}

	public Ruedas(Coches coches) {
		this.coches = coches;
	}

	public Ruedas(Coches coches, Integer pulgadas, String tipoNeumatico,
			Integer peso) {
		this.coches = coches;
		this.pulgadas = pulgadas;
		this.tipoNeumatico = tipoNeumatico;
		this.peso = peso;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_coches", nullable = false)
	public Coches getCoches() {
		return this.coches;
	}

	public void setCoches(Coches coches) {
		this.coches = coches;
	}

	@Column(name = "pulgadas")
	public Integer getPulgadas() {
		return this.pulgadas;
	}

	public void setPulgadas(Integer pulgadas) {
		this.pulgadas = pulgadas;
	}

	@Column(name = "tipo_neumatico", length = 50)
	public String getTipoNeumatico() {
		return this.tipoNeumatico;
	}

	public void setTipoNeumatico(String tipoNeumatico) {
		this.tipoNeumatico = tipoNeumatico;
	}

	@Column(name = "peso")
	public Integer getPeso() {
		return this.peso;
	}

	public void setPeso(Integer peso) {
		this.peso = peso;
	}

}
